// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsRegEx")>]
[<assembly: AssemblyProductAttribute("FsRegEx")>]
[<assembly: AssemblyDescriptionAttribute("Composable F# regular expressions.")>]
[<assembly: AssemblyVersionAttribute("0.7.2")>]
[<assembly: AssemblyFileVersionAttribute("0.7.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsRegEx"
    let [<Literal>] AssemblyProduct = "FsRegEx"
    let [<Literal>] AssemblyDescription = "Composable F# regular expressions."
    let [<Literal>] AssemblyVersion = "0.7.2"
    let [<Literal>] AssemblyFileVersion = "0.7.2"
    let [<Literal>] AssemblyConfiguration = "Release"
